Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -58,13 +58,34 @@ build:
         local machine_name=$1
         mkdir -p /images/${machine_name}
         echo "Debug level 1"
-        docker exec build bash -lc 'test -f "${WORK_DIR}/qcom-6.18-qli.2.0-ver.1.0_22.04/build/tmp/deploy/images/${machine_name}/qcom-multimedia-image-${machine_name}.rootfs.qcomflash.tar.gz" && echo "FOUND File" || echo "MISSING File"'
-        docker exec build bash -lc 'test -d "${WORK_DIR}/qcom-6.18-qli.2.0-ver.1.0_22.04/build/tmp/deploy/images/${machine_name}" && echo "Dir OK" || echo "MISSING DIR"'
+        SYMLINK_PATH="${WORK_DIR}/qcom-6.18-qli.2.0-ver.1.0_22.04/build/tmp/deploy/images/${machine_name}/qcom-multimedia-image-${machine_name}.rootfs.qcomflash.tar.gz"
+        # Resolve real file inside container
+        REAL_FILE=$(docker exec -e WORK_DIR="$WORK_DIR" -e machine_name="$machine_name" build \
+            bash -lc "readlink -f \"$SYMLINK_PATH\"")
+        echo "Real File for $SYMLINK_PATH is $REAL_FILE"
+        DEST_DIR="/images/${machine_name}"
+        # Rename output to symlink name
+        DEST_FILE="$DEST_DIR/$(basename "$SYMLINK_PATH")"
+        # Copy actual file but save with symlink name
+        docker cp "${CONTAINER}:${REAL_FILE}" "$DEST_FILE"
+
+        SYMLINK_PATH="${WORK_DIR}/qcom-6.18-qli.2.0-ver.1.0_22.04/build/tmp/deploy/images/${machine_name}/qcom-multimedia-proprietary-image-${machine_name}.rootfs.qcomflash.tar.gz"
+        # Resolve real file inside container
+        REAL_FILE=$(docker exec -e WORK_DIR="$WORK_DIR" -e machine_name="$machine_name" build \
+            bash -lc "readlink -f \"$SYMLINK_PATH\"")
+        echo "Real File for $SYMLINK_PATH is $REAL_FILE"
+        DEST_DIR="/images/${machine_name}"
+        # Rename output to symlink name
+        DEST_FILE="$DEST_DIR/$(basename "$SYMLINK_PATH")"
+        # Copy actual file but save with symlink name
+        docker cp "${CONTAINER}:${REAL_FILE}" "$DEST_FILE"
+        #docker exec build bash -lc 'test -f "${WORK_DIR}/qcom-6.18-qli.2.0-ver.1.0_22.04/build/tmp/deploy/images/${machine_name}/qcom-multimedia-image-${machine_name}.rootfs.qcomflash.tar.gz" && echo "FOUND File" || echo "MISSING File"'
+        #docker exec build bash -lc 'test -d "${WORK_DIR}/qcom-6.18-qli.2.0-ver.1.0_22.04/build/tmp/deploy/images/${machine_name}" && echo "Dir OK" || echo "MISSING DIR"'
         #tar -xzvf build:${WORK_DIR}/qcom-6.18-qli.2.0-ver.1.0_22.04/build/tmp/deploy/images/${machine_name}/qcom-multimedia-image-${machine_name}.rootfs.qcomflash.tar.gz /images/${machine_name}/
-        docker cp "build:${WORK_DIR}/qcom-6.18-qli.2.0-ver.1.0_22.04/build/tmp/deploy/images/${machine_name}/qcom-multimedia-image-${machine_name}.rootfs.qcomflash.tar.gz" "/images/${machine_name}/"
+        #docker cp "build:${WORK_DIR}/qcom-6.18-qli.2.0-ver.1.0_22.04/build/tmp/deploy/images/${machine_name}/qcom-multimedia-image-${machine_name}.rootfs.qcomflash.tar.gz" "/images/${machine_name}/"
         echo "Debug level 2"
         #tar -xzvf build:${WORK_DIR}/qcom-6.18-qli.2.0-ver.1.0_22.04/build/tmp/deploy/images/${machine_name}/qcom-multimedia-proprietary-image-${machine_name}.rootfs.qcomflash.tar.gz /images/${machine_name}/
-        docker cp "build:${WORK_DIR}/qcom-6.18-qli.2.0-ver.1.0_22.04/build/tmp/deploy/images/${machine_name}/qcom-multimedia-proprietary-image-${machine_name}.rootfs.qcomflash.tar.gz" "/images/${machine_name}/"
+        #docker cp "build:${WORK_DIR}/qcom-6.18-qli.2.0-ver.1.0_22.04/build/tmp/deploy/images/${machine_name}/qcom-multimedia-proprietary-image-${machine_name}.rootfs.qcomflash.tar.gz" "/images/${machine_name}/"
         echo "Debug level 3"
         docker cp build:${WORK_DIR}/qcom-6.18-qli.2.0-ver.1.0_22.04/NOTICE /images/${machine_name}/
         echo "Debug level 4"
